### ISSUE TITLE
bug  SendSyncMsg panic

### ISSUE THREAD

**Issue by Billxunyang** [UnderTreeTech/waterdrop#142]
11:49:16: panic: runtime error: invalid memory address or nil pointer dereference
11:49:16: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x972032]
11:49:16: goroutine 14820 [running]:
11:49:16: github.com/apache/rocketmq-client-go/v2/primitive.(*MessageQueue).String(...)
11:49:16: /go/pkg/mod/github.com/apache/rocketmq-client-go/v2@v2.0.0/primitive/message.go:393
11:49:16: github.com/apache/rocketmq-client-go/v2/primitive.(*SendResult).String(0xc000ee1320, 0x7, 0xc00000b700)
11:49:16: /go/pkg/mod/github.com/apache/rocketmq-client-go/v2@v2.0.0/primitive/result.go:56 +0x52
11:49:16: github.com/UnderTreeTech/waterdrop/pkg/broker/rocketmq.producerMetricInterceptor.func1(0xf693c0, 0xc0011d8450, 0xdf1fe0, 0xc000278000, 0xcee080, 0xc000ee1320, 0xc0003f6370, 0xc0011d8450, 0xc00020a200)
11:49:16: /go/pkg/mod/github.com/!under!tree!tech/waterdrop@v1.3.2/pkg/broker/rocketmq/interceptor.go:55 +0x45e
11:49:16: github.com/apache/rocketmq-client-go/v2/producer.(*defaultProducer).SendSync(0xc0004f0180, 0xf69340, 0xc000036110, 0xc0000b01c8, 0x1, 0x1, 0x74, 0xc0000b01c8, 0x1)
11:49:16: /go/pkg/mod/github.com/apache/rocketmq-client-go/v2@v2.0.0/producer/producer.go:163 +0x2e3
11:49:16: github.com/UnderTreeTech/waterdrop/pkg/broker/rocketmq.(*Producer).SendSyncMsg(0xc0004ff920, 0xf69340, 0xc000036110, 0xc00020a180, 0x74, 0x74, 0x0)

**Comment by UnderTreeTech** [comment]
fixed. [eebcf35](https://github.com/UnderTreeTech/waterdrop/commit/eebcf356db57a755e3a9ce72c27d2af025d998f8)
