### ISSUE TITLE
能提供个分布式事务的例子吗？

### ISSUE THREAD

**Issue by Leadrive** [UnderTreeTech/waterdrop#68]
想试用下你的框架，重点想关注下事务这块。
能提供一个例子吗？数据库是mysql。
谢谢。

**Comment by UnderTreeTech** [comment]
分布式事务要看业务场景需要刚性事务还是柔性事务，选择方案会不同。框架不会支持分布式事务，太偏业务了。提供一种思路[分布式事务](https://github.com/UnderTreeTech/waterdrop/issues/69) ， 你可以尝试。

**Comment by Leadrive** [comment]
其实，我是觉得是可以把XA事务，在框架内实现掉的。
超时，无法完成的，只能人工去处理。但自动 部分，是可以在框架内完成。
